/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as BookingRouteImport } from './routes/booking'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminShellRouteImport } from './routes/admin/_shell'
import { Route as AdminShellIndexRouteImport } from './routes/admin/_shell/index'
import { Route as AdminShellPaymentsIndexRouteImport } from './routes/admin/_shell/payments.index'
import { Route as AdminShellFleetIndexRouteImport } from './routes/admin/_shell/fleet.index'
import { Route as AdminShellClientsIndexRouteImport } from './routes/admin/_shell/clients.index'
import { Route as AdminShellBookingsIndexRouteImport } from './routes/admin/_shell/bookings.index'
import { Route as AdminShellFleetCarIdRouteImport } from './routes/admin/_shell/fleet.$carId'
import { Route as AdminShellClientsClientIdRouteImport } from './routes/admin/_shell/clients.$clientId'
import { Route as AdminShellBookingsNewRouteImport } from './routes/admin/_shell/bookings.new'
import { Route as AdminShellBookingsBookingIdRouteImport } from './routes/admin/_shell/bookings.$bookingId'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingRoute = BookingRouteImport.update({
  id: '/booking',
  path: '/booking',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminShellRoute = AdminShellRouteImport.update({
  id: '/admin/_shell',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminShellIndexRoute = AdminShellIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminShellRoute,
} as any)
const AdminShellPaymentsIndexRoute = AdminShellPaymentsIndexRouteImport.update({
  id: '/payments/',
  path: '/payments/',
  getParentRoute: () => AdminShellRoute,
} as any)
const AdminShellFleetIndexRoute = AdminShellFleetIndexRouteImport.update({
  id: '/fleet/',
  path: '/fleet/',
  getParentRoute: () => AdminShellRoute,
} as any)
const AdminShellClientsIndexRoute = AdminShellClientsIndexRouteImport.update({
  id: '/clients/',
  path: '/clients/',
  getParentRoute: () => AdminShellRoute,
} as any)
const AdminShellBookingsIndexRoute = AdminShellBookingsIndexRouteImport.update({
  id: '/bookings/',
  path: '/bookings/',
  getParentRoute: () => AdminShellRoute,
} as any)
const AdminShellFleetCarIdRoute = AdminShellFleetCarIdRouteImport.update({
  id: '/fleet/$carId',
  path: '/fleet/$carId',
  getParentRoute: () => AdminShellRoute,
} as any)
const AdminShellClientsClientIdRoute =
  AdminShellClientsClientIdRouteImport.update({
    id: '/clients/$clientId',
    path: '/clients/$clientId',
    getParentRoute: () => AdminShellRoute,
  } as any)
const AdminShellBookingsNewRoute = AdminShellBookingsNewRouteImport.update({
  id: '/bookings/new',
  path: '/bookings/new',
  getParentRoute: () => AdminShellRoute,
} as any)
const AdminShellBookingsBookingIdRoute =
  AdminShellBookingsBookingIdRouteImport.update({
    id: '/bookings/$bookingId',
    path: '/bookings/$bookingId',
    getParentRoute: () => AdminShellRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/booking': typeof BookingRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin': typeof AdminShellRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/admin/': typeof AdminShellIndexRoute
  '/admin/bookings/$bookingId': typeof AdminShellBookingsBookingIdRoute
  '/admin/bookings/new': typeof AdminShellBookingsNewRoute
  '/admin/clients/$clientId': typeof AdminShellClientsClientIdRoute
  '/admin/fleet/$carId': typeof AdminShellFleetCarIdRoute
  '/admin/bookings/': typeof AdminShellBookingsIndexRoute
  '/admin/clients/': typeof AdminShellClientsIndexRoute
  '/admin/fleet/': typeof AdminShellFleetIndexRoute
  '/admin/payments/': typeof AdminShellPaymentsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/booking': typeof BookingRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin': typeof AdminShellIndexRoute
  '/admin/bookings/$bookingId': typeof AdminShellBookingsBookingIdRoute
  '/admin/bookings/new': typeof AdminShellBookingsNewRoute
  '/admin/clients/$clientId': typeof AdminShellClientsClientIdRoute
  '/admin/fleet/$carId': typeof AdminShellFleetCarIdRoute
  '/admin/bookings': typeof AdminShellBookingsIndexRoute
  '/admin/clients': typeof AdminShellClientsIndexRoute
  '/admin/fleet': typeof AdminShellFleetIndexRoute
  '/admin/payments': typeof AdminShellPaymentsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/booking': typeof BookingRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/_shell': typeof AdminShellRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/admin/_shell/': typeof AdminShellIndexRoute
  '/admin/_shell/bookings/$bookingId': typeof AdminShellBookingsBookingIdRoute
  '/admin/_shell/bookings/new': typeof AdminShellBookingsNewRoute
  '/admin/_shell/clients/$clientId': typeof AdminShellClientsClientIdRoute
  '/admin/_shell/fleet/$carId': typeof AdminShellFleetCarIdRoute
  '/admin/_shell/bookings/': typeof AdminShellBookingsIndexRoute
  '/admin/_shell/clients/': typeof AdminShellClientsIndexRoute
  '/admin/_shell/fleet/': typeof AdminShellFleetIndexRoute
  '/admin/_shell/payments/': typeof AdminShellPaymentsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/booking'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/admin'
    | '/admin/login'
    | '/admin/'
    | '/admin/bookings/$bookingId'
    | '/admin/bookings/new'
    | '/admin/clients/$clientId'
    | '/admin/fleet/$carId'
    | '/admin/bookings/'
    | '/admin/clients/'
    | '/admin/fleet/'
    | '/admin/payments/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/booking'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/admin/login'
    | '/admin'
    | '/admin/bookings/$bookingId'
    | '/admin/bookings/new'
    | '/admin/clients/$clientId'
    | '/admin/fleet/$carId'
    | '/admin/bookings'
    | '/admin/clients'
    | '/admin/fleet'
    | '/admin/payments'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/booking'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/admin/_shell'
    | '/admin/login'
    | '/admin/_shell/'
    | '/admin/_shell/bookings/$bookingId'
    | '/admin/_shell/bookings/new'
    | '/admin/_shell/clients/$clientId'
    | '/admin/_shell/fleet/$carId'
    | '/admin/_shell/bookings/'
    | '/admin/_shell/clients/'
    | '/admin/_shell/fleet/'
    | '/admin/_shell/payments/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BookingRoute: typeof BookingRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  AdminShellRoute: typeof AdminShellRouteWithChildren
  AdminLoginRoute: typeof AdminLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking': {
      id: '/booking'
      path: '/booking'
      fullPath: '/booking'
      preLoaderRoute: typeof BookingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/_shell': {
      id: '/admin/_shell'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminShellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/_shell/': {
      id: '/admin/_shell/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminShellIndexRouteImport
      parentRoute: typeof AdminShellRoute
    }
    '/admin/_shell/payments/': {
      id: '/admin/_shell/payments/'
      path: '/payments'
      fullPath: '/admin/payments/'
      preLoaderRoute: typeof AdminShellPaymentsIndexRouteImport
      parentRoute: typeof AdminShellRoute
    }
    '/admin/_shell/fleet/': {
      id: '/admin/_shell/fleet/'
      path: '/fleet'
      fullPath: '/admin/fleet/'
      preLoaderRoute: typeof AdminShellFleetIndexRouteImport
      parentRoute: typeof AdminShellRoute
    }
    '/admin/_shell/clients/': {
      id: '/admin/_shell/clients/'
      path: '/clients'
      fullPath: '/admin/clients/'
      preLoaderRoute: typeof AdminShellClientsIndexRouteImport
      parentRoute: typeof AdminShellRoute
    }
    '/admin/_shell/bookings/': {
      id: '/admin/_shell/bookings/'
      path: '/bookings'
      fullPath: '/admin/bookings/'
      preLoaderRoute: typeof AdminShellBookingsIndexRouteImport
      parentRoute: typeof AdminShellRoute
    }
    '/admin/_shell/fleet/$carId': {
      id: '/admin/_shell/fleet/$carId'
      path: '/fleet/$carId'
      fullPath: '/admin/fleet/$carId'
      preLoaderRoute: typeof AdminShellFleetCarIdRouteImport
      parentRoute: typeof AdminShellRoute
    }
    '/admin/_shell/clients/$clientId': {
      id: '/admin/_shell/clients/$clientId'
      path: '/clients/$clientId'
      fullPath: '/admin/clients/$clientId'
      preLoaderRoute: typeof AdminShellClientsClientIdRouteImport
      parentRoute: typeof AdminShellRoute
    }
    '/admin/_shell/bookings/new': {
      id: '/admin/_shell/bookings/new'
      path: '/bookings/new'
      fullPath: '/admin/bookings/new'
      preLoaderRoute: typeof AdminShellBookingsNewRouteImport
      parentRoute: typeof AdminShellRoute
    }
    '/admin/_shell/bookings/$bookingId': {
      id: '/admin/_shell/bookings/$bookingId'
      path: '/bookings/$bookingId'
      fullPath: '/admin/bookings/$bookingId'
      preLoaderRoute: typeof AdminShellBookingsBookingIdRouteImport
      parentRoute: typeof AdminShellRoute
    }
  }
}

interface AdminShellRouteChildren {
  AdminShellIndexRoute: typeof AdminShellIndexRoute
  AdminShellBookingsBookingIdRoute: typeof AdminShellBookingsBookingIdRoute
  AdminShellBookingsNewRoute: typeof AdminShellBookingsNewRoute
  AdminShellClientsClientIdRoute: typeof AdminShellClientsClientIdRoute
  AdminShellFleetCarIdRoute: typeof AdminShellFleetCarIdRoute
  AdminShellBookingsIndexRoute: typeof AdminShellBookingsIndexRoute
  AdminShellClientsIndexRoute: typeof AdminShellClientsIndexRoute
  AdminShellFleetIndexRoute: typeof AdminShellFleetIndexRoute
  AdminShellPaymentsIndexRoute: typeof AdminShellPaymentsIndexRoute
}

const AdminShellRouteChildren: AdminShellRouteChildren = {
  AdminShellIndexRoute: AdminShellIndexRoute,
  AdminShellBookingsBookingIdRoute: AdminShellBookingsBookingIdRoute,
  AdminShellBookingsNewRoute: AdminShellBookingsNewRoute,
  AdminShellClientsClientIdRoute: AdminShellClientsClientIdRoute,
  AdminShellFleetCarIdRoute: AdminShellFleetCarIdRoute,
  AdminShellBookingsIndexRoute: AdminShellBookingsIndexRoute,
  AdminShellClientsIndexRoute: AdminShellClientsIndexRoute,
  AdminShellFleetIndexRoute: AdminShellFleetIndexRoute,
  AdminShellPaymentsIndexRoute: AdminShellPaymentsIndexRoute,
}

const AdminShellRouteWithChildren = AdminShellRoute._addFileChildren(
  AdminShellRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BookingRoute: BookingRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  AdminShellRoute: AdminShellRouteWithChildren,
  AdminLoginRoute: AdminLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
